# Generated by Django 6.0.1 on 2026-04-13 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=150, unique=True)),
                ('password', models.CharField(db_column='password_hash', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked')], db_column='status', default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('role', models.ForeignKey(db_column='role_id', help_text='Rol del usuario.', on_delete=django.db.models.deletion.PROTECT, related_name='users', to='roles.role')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deleted_at'], name='idx_users_deleted_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'blocked'])), name='chk_users_status_valid')],
            },
        ),
    ]
