# Generated by Django 6.0.1 on 2026-04-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', help_text='ID del usuario que realizó la petición (sin FK para preservar el log).', null=True)),
                ('ip_address', models.CharField(db_column='ip_address', help_text='IPv4 (max 15 chars) o IPv6 (max 45 chars).', max_length=45)),
                ('request_path', models.CharField(db_column='request_path', help_text='Ruta completa de la petición, ej: /api/v1/deployments/', max_length=500)),
                ('action', models.CharField(db_column='action', help_text='Descripción de la acción realizada, ej: USER_LOGIN, SITE_UPLOAD.', max_length=100)),
                ('http_method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE'), ('OPTIONS', 'OPTIONS'), ('HEAD', 'HEAD')], db_column='http_method', max_length=10)),
                ('status_code', models.IntegerField(db_column='status_code', help_text='Código HTTP de respuesta, ej: 200, 201, 400, 404, 500.')),
                ('user_agent', models.CharField(blank=True, db_column='user_agent', default='', help_text='User-Agent del cliente que realizó la petición.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'verbose_name': 'System Log',
                'verbose_name_plural': 'System Logs',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='idx_system_logs_user_id'), models.Index(fields=['ip_address'], name='idx_system_logs_ip'), models.Index(fields=['action'], name='idx_system_logs_action'), models.Index(fields=['status_code'], name='idx_system_logs_status_code'), models.Index(fields=['created_at'], name='idx_system_logs_created_at')],
            },
        ),
    ]
