# Generated by Django 6.0.1 on 2026-04-13 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system_logs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='user',
            field=models.ForeignKey(blank=True, db_column='user_id', help_text='Usuario que realizó la petición (FK; se permite null).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['ip_address'], name='idx_system_logs_ip'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['action'], name='idx_system_logs_action'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['status_code'], name='idx_system_logs_status_code'),
        ),
        migrations.AddIndex(
            model_name='systemlog',
            index=models.Index(fields=['created_at'], name='idx_system_logs_created_at'),
        ),
    ]
