# Generated by Django 6.0.1 on 2026-04-13 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('months_requested', models.IntegerField(blank=True, db_column='months_requested', help_text='Meses solicitados para el nuevo plan. Ej: 1, 3, 6, 12.', null=True)),
                ('total_price', models.DecimalField(blank=True, db_column='total_price', decimal_places=2, help_text='Monto total estimado para la solicitud (plan_price * meses).', max_digits=10, null=True)),
                ('reason', models.CharField(blank=True, db_column='reason', default='', help_text='Razón o motivo del cambio de plan.', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_column='status', default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, db_column='reviewed_at', help_text='Fecha y hora en que se revisó la solicitud.', null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_column='completed_at', help_text='Fecha y hora en que se completó el cambio de plan.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
            ],
            options={
                'verbose_name': 'Plan Change Request',
                'verbose_name_plural': 'Plan Change Requests',
                'db_table': 'plan_change_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
