# Generated by Django 6.0.1 on 2026-04-12 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_change_request', '0001_initial'),
        ('plans', '0001_initial'),
        ('user_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planchangerequest',
            name='current_plan',
            field=models.ForeignKey(db_column='current_plan_id', help_text='Plan actual del usuario (UserPlan activo).', on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_from', to='user_plans.userplan'),
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='requested_plan',
            field=models.ForeignKey(db_column='requested_plan_id', help_text='Plan al que el usuario desea cambiar.', on_delete=django.db.models.deletion.PROTECT, related_name='change_requests_to', to='plans.plan'),
        ),
    ]
