# Generated by Django 6.0.1 on 2026-04-11 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plan_change_request', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planchangerequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_column='reviewed_by_id', help_text='Usuario administrador que revisó la solicitud.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_plan_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planchangerequest',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='Usuario que solicita el cambio de plan.', on_delete=django.db.models.deletion.CASCADE, related_name='plan_change_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['user'], name='idx_plan_change_req_user_id'),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['current_plan'], name='idx_plan_change_req_current'),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['requested_plan'], name='idx_plan_change_req_requested'),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['status'], name='idx_plan_change_req_status'),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['reviewed_by'], name='idx_plan_change_req_reviewer'),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['created_at'], name='idx_plan_change_req_created_at'),
        ),
        migrations.AddIndex(
            model_name='planchangerequest',
            index=models.Index(fields=['deleted_at'], name='idx_plan_change_req_deleted_at'),
        ),
    ]
