# como le pusimos en sonar
sonar.projectKey=back-vss
sonar.projectName=back-vss
sonar.projectVersion=1.0

# Codigo fuente Python del proyecto
# poner la estructura del back que tengo configurado
sonar.sources=BackVantardSoftwareStudio,core
sonar.sourceEncoding=UTF-8

# Analizar solo archivos Python
sonar.inclusions=**/*.py

# Excluir artefactos no relevantes
sonar.exclusions=**/migrations/**,**/__pycache__/**,**/venv/**,**/env/**,**/*.pyc,**/node_modules/**,**/static/**

# Tests
# para saber donde estas mis test
#sonar.tests=apps
#sonar.test.inclusions=**/tests/**/*.py,**/test_*.py
