# Generated by Django 6.0.1 on 2026-03-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(db_column='version_number', help_text='Numero de version incremental dentro del deployment. Ej: 1, 2, 3...')),
                ('zip_filename', models.CharField(db_column='zip_filename', help_text='Nombre original del archivo .zip subido. Ej: mi-sitio-v2.zip', max_length=255)),
                ('zip_path', models.CharField(db_column='zip_path', help_text='Ruta en el servidor donde se almacena el .zip. Ej: uploads/deployments/1/v2/mi-sitio.zip', max_length=500)),
                ('disk_used_mb', models.IntegerField(db_column='disk_used_mb', default=0, help_text='Espacio en disco que ocupa esta version en MB.')),
                ('traffic_log_path', models.CharField(blank=True, db_column='traffic_log_path', default='', help_text='Ruta al archivo de log de trafico de esta version. Puede estar vacio.', max_length=500)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed'), ('archived', 'Archived')], db_column='status', default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
            ],
            options={
                'verbose_name': 'Deployment Version',
                'verbose_name_plural': 'Deployment Versions',
                'db_table': 'deployment_versions',
                'ordering': ['-version_number'],
            },
        ),
    ]
