# Generated by Django 6.0.1 on 2026-04-11 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployment_version', '0001_initial'),
        ('deployments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deploymentversion',
            name='deployment',
            field=models.ForeignKey(db_column='deployment_id', help_text='Deployment al que pertenece esta version.', on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='deployments.deployment'),
        ),
        migrations.AddIndex(
            model_name='deploymentversion',
            index=models.Index(fields=['deployment'], name='idx_depver_deployment_id'),
        ),
        migrations.AddIndex(
            model_name='deploymentversion',
            index=models.Index(fields=['status'], name='idx_depver_status'),
        ),
        migrations.AddIndex(
            model_name='deploymentversion',
            index=models.Index(fields=['version_number'], name='idx_depver_version_number'),
        ),
        migrations.AddIndex(
            model_name='deploymentversion',
            index=models.Index(fields=['created_at'], name='idx_depver_created_at'),
        ),
        migrations.AddIndex(
            model_name='deploymentversion',
            index=models.Index(fields=['deleted_at'], name='idx_depver_deleted_at'),
        ),
        migrations.AddConstraint(
            model_name='deploymentversion',
            constraint=models.UniqueConstraint(fields=('deployment', 'version_number'), name='uq_deployment_version_number'),
        ),
    ]
