# Generated by Django 6.0.1 on 2026-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_column='domain', max_length=255)),
                ('site_url', models.CharField(db_column='site_url', max_length=255)),
                ('version_number', models.IntegerField(db_column='version_number', default=0, help_text='Número incremental de versión para este despliegue (comienza en 0 y se incrementa en cada subida de ZIP).')),
                ('zip_filename', models.CharField(blank=True, db_column='zip_filename', default='', help_text='Nombre original del último ZIP subido.', max_length=255)),
                ('zip_path', models.CharField(blank=True, db_column='zip_path', default='', help_text='Ruta (relativa a MEDIA_ROOT) del último ZIP subido.', max_length=500)),
                ('disk_used_mb', models.IntegerField(db_column='disk_used_mb', default=0)),
                ('traffic_visit_count', models.IntegerField(db_column='traffic_visit_count', default=0)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('blocked', 'Bloqueado'), ('inactive', 'Inactivo'), ('replaced', 'Reemplazado'), ('failed', 'Fallido')], db_column='status', default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
            ],
            options={
                'verbose_name': 'Despliegue',
                'verbose_name_plural': 'Despliegues',
                'db_table': 'deployments',
                'ordering': ['-created_at'],
            },
        ),
    ]
