# Generated by Django 6.0.1 on 2026-04-13 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['created_at'], name='idx_deployments_created_at'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['deleted_at'], name='idx_deployments_deleted_at'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'blocked', 'inactive', 'replaced', 'failed'])), name='chk_deployments_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(fields=('user', 'version_number'), name='uq_deployments_user_version_number'),
        ),
    ]
