# Generated by Django 6.0.1 on 2026-04-13 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(db_column='purchase_date', help_text='Fecha y hora en que se realizo la compra.')),
                ('expiration_date', models.DateTimeField(db_column='expiration_date', help_text='Fecha y hora en que vence la suscripcion.')),
                ('months_purchased', models.IntegerField(db_column='months_purchased', help_text='Cantidad de meses comprados en esta suscripcion. Ej: 1, 3, 6, 12.')),
                ('total_price_paid', models.DecimalField(db_column='total_price_paid', decimal_places=2, help_text='Precio total pagado en USD (precio_plan * meses). Ej: 29.97 por 3 meses a 9.99.', max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_column='status', default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
                ('plan', models.ForeignKey(db_column='plan_id', help_text='Plan adquirido.', on_delete=django.db.models.deletion.PROTECT, related_name='user_plans', to='plans.plan')),
            ],
            options={
                'verbose_name': 'User Plan',
                'verbose_name_plural': 'User Plans',
                'db_table': 'user_plans',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
