# Generated by Django 6.0.1 on 2026-04-11 21:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='Usuario que adquirio el plan.', on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['user'], name='idx_user_plans_user_id'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['plan'], name='idx_user_plans_plan_id'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['status'], name='idx_user_plans_status'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['purchase_date'], name='idx_user_plans_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['expiration_date'], name='idx_user_plans_expiration_date'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['deleted_at'], name='idx_user_plans_deleted_at'),
        ),
    ]
