# Generated by Django 6.0.1 on 2026-04-13 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_plans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='user',
            field=models.ForeignKey(db_column='user_id', help_text='Usuario que adquirio el plan.', on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['purchase_date'], name='idx_user_plans_purchase_date'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['expiration_date'], name='idx_user_plans_expiration_date'),
        ),
        migrations.AddIndex(
            model_name='userplan',
            index=models.Index(fields=['deleted_at'], name='idx_user_plans_deleted_at'),
        ),
        migrations.AddConstraint(
            model_name='userplan',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'expired', 'cancelled'])), name='chk_user_plans_status_valid'),
        ),
    ]
