# Generated by Django 6.0.1 on 2026-04-13 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveUserWithPlan',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=150)),
                ('plan_name', models.CharField(db_column='plan_name', max_length=50)),
                ('expiration_date', models.DateTimeField(db_column='expiration_date')),
            ],
            options={
                'verbose_name': 'Active User With Plan',
                'verbose_name_plural': 'Active Users With Plan',
                'db_table': 'vw_active_users_with_plan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminDashboardStats',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('total_users', models.IntegerField(db_column='total_users')),
                ('active_users', models.IntegerField(db_column='active_users')),
                ('total_deployments', models.IntegerField(db_column='total_deployments')),
                ('active_deployments', models.IntegerField(db_column='active_deployments')),
                ('total_disk_used_mb', models.IntegerField(db_column='total_disk_used_mb')),
                ('total_traffic_visit_count', models.IntegerField(db_column='total_traffic_visit_count')),
            ],
            options={
                'verbose_name': 'Admin Dashboard Stat',
                'verbose_name_plural': 'Admin Dashboard Stats',
                'db_table': 'vw_admin_dashboard_stats',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminDeploymentStateCount',
            fields=[
                ('estado', models.CharField(db_column='estado', max_length=20, primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
            ],
            options={
                'verbose_name': 'Admin Deployment State Count',
                'verbose_name_plural': 'Admin Deployment State Counts',
                'db_table': 'vw_admin_deployment_state_counts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminPlanDistribution',
            fields=[
                ('id', models.BigIntegerField(db_column='id', primary_key=True, serialize=False)),
                ('plan_name', models.CharField(db_column='plan_name', max_length=50)),
                ('user_count', models.IntegerField(db_column='user_count')),
            ],
            options={
                'verbose_name': 'Admin Plan Distribution',
                'verbose_name_plural': 'Admin Plan Distribution',
                'db_table': 'vw_admin_plan_distribution',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserDashboardProfile',
            fields=[
                ('user_id', models.BigIntegerField(db_column='user_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='first_name', max_length=100)),
                ('last_name', models.CharField(db_column='last_name', max_length=100)),
                ('email', models.EmailField(db_column='email', max_length=150)),
                ('plan_name', models.CharField(blank=True, db_column='plan_name', max_length=50, null=True)),
                ('plan_max_disk_mb', models.IntegerField(db_column='plan_max_disk_mb')),
                ('used_disk_mb', models.IntegerField(db_column='used_disk_mb')),
                ('total_traffic_visit_count', models.IntegerField(db_column='total_traffic_visit_count')),
                ('active_site_domain', models.CharField(blank=True, db_column='active_site_domain', max_length=255, null=True)),
                ('active_site_disk_used_mb', models.IntegerField(blank=True, db_column='active_site_disk_used_mb', null=True)),
            ],
            options={
                'verbose_name': 'User Dashboard Profile',
                'verbose_name_plural': 'User Dashboard Profiles',
                'db_table': 'vw_user_dashboard_profile',
                'managed': False,
            },
        ),
    ]
