# Generated by Django 6.0.1 on 2026-04-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', help_text='Nombre del plan, ej: Free, Basic, Pro, Enterprise.', max_length=50, unique=True)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, help_text='Precio del plan en USD. Ej: 0.00 para Free, 9.99 para Basic.', max_digits=10)),
                ('max_disk_mb', models.IntegerField(db_column='max_disk_mb', help_text='Límite de almacenamiento en MB. Ej: 500, 2048, 10240.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_column='status', default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('deleted_at', models.DateTimeField(blank=True, db_column='deleted_at', null=True)),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
                'db_table': 'plans',
                'ordering': ['price'],
                'indexes': [models.Index(fields=['deleted_at'], name='idx_plans_deleted_at')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive'])), name='chk_plans_status_valid')],
            },
        ),
    ]
